### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#16]
The site is down
https://lccn.lbao.site/
https://lccn.lbao.site/predicted/biweekly-contest-105

Is there a way to help you so site can be up - post contests?

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/a6749ed4-eb88-4749-9d2d-6152882e3b4d)

**Comment by baoliay2008** [comment]
Server was down, but I brought it up. MongoDB's high memory usage may be the root cause, which I'm investigating.

**Comment by manoharreddyporeddy** [comment]
Investigation can continue.
For now, server is back online & no issues in last few contests.
