### ISSUE TITLE
Username history is lost

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#18]
When I click the username textbox
I used to get a popup of previous searched usernames

Today it didn't come up
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/3126caef-7718-42ad-b630-dcde363a96c3)

Even after I searched for a username, it does not show up popup of recently searched usernames
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/d4861e69-5923-416c-b5ef-76185df623a2)

It is good to show last 50 or so searched usernames, in a drop down with a scroll bar ( previously it used to show only 5 or so )
thank you for your efforts & time.

**Comment by alpha951** [comment]
The username history is visible for me. It depned on your browser cookies. You might have cleared cache while clearing browser history.

**Comment by manoharreddyporeddy** [comment]
looks like
the chrome changed the way it works after recent update
i used to be logged in in the toolbar too, now no more ( also no option to login there, just shows Person 1 for now )

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/36d8c4ba-56d5-468f-9ffd-8b29985e44f6)

**Comment by manoharreddyporeddy** [comment]
Looks like, it is do with my laptop too. All good.
