### ISSUE TITLE
Color in Rank Change (Delta) should be reversed

### ISSUE THREAD

**Issue by Akay-Code** [baoliay2008/lccn_predictor#19]
On the main website change of each rating (delta) has red color shade for positive rating and Green color for negative rating change.
This seems so off ,  an Improvement should be represented by Green color and decrement in rating with Red.

![image](https://github.com/baoliay2008/lccn_predictor/assets/93380151/98dee02e-b9c2-4e9f-9619-10ecdfbe7881)

If this seems to be an Issue. Kindly assign this to me.

**Comment by manoharreddyporeddy** [comment]
As this question is common, and different countries have different meaning for colors,
providing a toggle button will help
@baoliay2008
