### ISSUE TITLE
change in Delta value fill color for contest predictions.

### ISSUE THREAD

**Issue by amitpant14** [baoliay2008/lccn_predictor#2]
Currently, when there is a positive change in rating, it is depicted in red color and is green on negative changes. I think it would be better to use green color to reflect positive changes and red for negative ones.

**Comment by baoliay2008** [comment]
Hi, @amitpant14 thank you for mentioning this.

Here are some cultural differences, usually red means up and green means down in some countries like China, Korea, Japan, etc. (like stocks, [reference](https://graphicdesign.stackexchange.com/questions/6982/except-china-which-country-will-use-red-for-up-and-green-for-down))

I'm working on a new version of building webpages using React, and the current pages will be deprecated. So I will try to set the fill color for different countries.

**Comment by amitpant14** [comment]
@baoliay2008 I see. Thanks for clarifying. I didn't know about this.

**Comment by baoliay2008** [comment]
This feature has been successfully implemented. Now, we automatically detect the user's browser language preference and customize the color scheme based on regional configurations.

For instance, Chinese and Japanese users will experience a color scheme of `up: 🟥, down: 🟩`, while Korean users will see `up: 🟥, down: 🟦`. By default, users in other regions, such as North America, Europe, and India, will encounter `up: 🟩, down: 🟥`.

For details, please check 3404fade22b6eb7a9be4b6114fe4bb9baebdd302
