### ISSUE TITLE
Graph is invisible

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#21]
Looks like the graph is not visible anymore

https://lccn.lbao.site/predicted/biweekly-contest-109

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/7d763f30-530e-4b81-958d-76cd3a24db58)

**Comment by maityamit** [comment]
@baoliay2008 Ya, Please look into this issue. The graph is invisible from yesterday. Main Graph as well as participants Graph.

**Comment by baoliay2008** [comment]
Appreciate your feedback, I'll promptly address this matter.

**Comment by manoharreddyporeddy** [comment]
I have verified
	last 5 contests
	graph is visible & working fine

Thank you @baoliay2008 

. https://lccn.lbao.site/predicted/weekly-contest-355
. https://lccn.lbao.site/predicted/biweekly-contest-109
. https://lccn.lbao.site/predicted/weekly-contest-354
. https://lccn.lbao.site/predicted/weekly-contest-353
. https://lccn.lbao.site/predicted/biweekly-contest-108
