### ISSUE TITLE
Site is down - Aug 5, 2023

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#22]
Thanks for the website & hard work you put in.

===

I have been mentioning https://lccn.lbao.site/ in many places and possibly many others.
Site may be more popular now than in last few months, so might need little upgrade.

Today either timeout or below continuous loading bar comes up:
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/7541f036-a6ef-4d26-84f4-138981aec9fa)

Both home page & current contest page is down
. https://lccn.lbao.site/
. https://lccn.lbao.site/predicted/biweekly-contest-110

Also unable to see previous contests.

**Comment by baoliay2008** [comment]
Hello, thank you for reporting this issue. I have recently restored the server. 

It appears that the save_real_time_rank function is consuming excessive memory, which is causing problems on machines with limited memory, such as my cloud machine. I will address this concern by considering a rewrite of the function to optimize its memory usage.

**Comment by baoliay2008** [comment]
Indeed, the issue led to at least three instances of OOM (Out of Memory) on the cloud machine (#21, #16). Rest assured, I will take immediate action to resolve this problem and optimize the memory usage of the `save_real_time_rank` function.

Also, I extend my heartfelt gratitude for bringing attention to my project! Your support is greatly appreciated!

**Comment by baoliay2008** [comment]
Hello @manoharreddyporeddy, thank you for opening this issue. Please note that the root cause has been identified, and this issue has been fixed(51e5de955b5341858d05c41aac2dd56a4611fffc).

**Comment by manoharreddyporeddy** [comment]
Thanks for your time & hardwork @baoliay2008 . Really appreciate it.
