### ISSUE TITLE
Weekly Contest 364 is missing

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#24]
Weekly Contest 364 https://leetcode.com/contest/weekly-contest-364/
contest has ended.

but ratings are not available

unable to access here - https://lccn.lbao.site/predicted/weekly-contest-364
and https://lccn.lbao.site/

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/e357be24-c240-456e-bf3a-1df0ed2a584b)
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/d231ddb7-77dd-40ec-a9f9-eb68935d5fac)

@baoliay2008 kindly look into it

**Comment by baoliay2008** [comment]
Hi, @manoharreddyporeddy . Please be aware that data synchronization between the LeetCode US and CN regions has not taken place. If you visit the following [URL](https://leetcode.com/contest/api/ranking/weekly-contest-364/), you will not find any `"data_region":"CN"` information available.

**Comment by Donavern** [comment]
Hi, it has been updated. We can close this now.

**Comment by baoliay2008** [comment]
Hi, @Donavern I have modified the server code to make it fetch data from the CN data_region.

However, please be aware that this is not a general solution. Sometimes, the case arises where the CN data_region does not fetch data from the US data_region. A trickier scenario is when there is incomplete synchronization, causing their total numbers to be very close but not the same, indicating that both regions have incomplete data.

Kindly leave the issue open and let me think about what the smarter way is.

**Comment by Donavern** [comment]
Hi @baoliay2008 , sure I did not realize that was how it worked.

Cheers 👍🏻

**Comment by manoharreddyporeddy** [comment]
thanks @baoliay2008 for details:

We may do as follows:

```
1 If US data_region has both data
	Fetch data from the US data_region
2 else If CN data_region has both data
	Fetch data from the CN data_region
3 else   (neither has both data)
	Fetch data from the US data_region

Both regions have incomplete data
	This is an edge case, already taken care by Point 1
```

Today point 3 is not done, so no prediction are shown.

Importantly, we have to note that:
1 Most users see prediction just after the contest ended ( when it's hot topic )
2 80% won't see prediction post 30 mins after the contest ended

**Comment by Codensity30** [comment]
Now, it's updated so you can close the issue as it's resolved. By the way, it's amazing to use 👏

**Comment by pedrosorio** [comment]
@baoliay2008 it seems like leetcode .com/.cn leaderboards were not merged after the contest (https://leetcode.com/contest/weekly-contest-364/ranking still has only .com users).

There have also been other changes: for the first time leetcode.com leaderboard shows the language used for each solution.

I have noticed the rating deltas are significantly different from predicted. Is it possible leetcode is now calculating the ratings independently for the two regions?

**Comment by baoliay2008** [comment]
@pedrosorio thanks for your suggestion. I also noticed that there were some changes in Contests API. But for weekly contest 364 there was a technical issue in `.cn` so they just unrated this contest in CN data region. I don't know whether it's a coincidence. I will keep my eye on it.

**Comment by baoliay2008** [comment]
@pedrosorio  I checked yesterday and found that these changes (adding the `lang` filed, missing `.cn` users) **started from `biweekly-contest-113` and `weekly-contest-363` in last week**, and I didn't see a huge inconsistency of rating prediction in these two contests.

**Comment by pedrosorio** [comment]
@baoliay2008 But if I visit the leaderboard for those contests (https://leetcode.com/contest/weekly-contest-363/ranking), I do not see the language icons and, more importantly, the leaderboard has users from both .com and .cn 

But yeah, given there were technical issues for 364 on the .cn side, this may have been a one time thing and ratings will update globally going forward.

**Comment by baoliay2008** [comment]
@pedrosorio  I know we cannot see it now, but that wasn't the case yesterday, and I added it as a to-do list item yesterday. Another way to check is that in the online app, there is no real-time rank history for .cn users since [biweekly-contest-113](https://lccn.lbao.site/predicted/biweekly-contest-113) because CN users were missing before.
