### ISSUE TITLE
Biweekly Contest 115 - Ranks are slightly off

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#25]
Biweekly Contest 115 ranks are slightly off

All users at below link have ranks between 3326 to 3350
https://leetcode.com/contest/biweekly-contest-115/ranking/134/

However, take any user, and check at below link, it shows ranks to have between 4130 to 4157
https://lccn.lbao.site/predicted/biweekly-contest-115

please look into this when possible @baoliay2008

**Comment by baoliay2008** [comment]
Hi, leetcode.com didn't sync with leetcode.cn, and if, when counting users from the CN region, it should be correct.
