### ISSUE TITLE
Navigating to different page numbers is difficult

### ISSUE THREAD

**Issue by sebat2004** [baoliay2008/lccn_predictor#26]
On the leetcode contests website, the URL is formatted like weekly-contest-367/ranking/<page_number>. This allows users to skip to a page number they want. On the prediction page, the URL is formatted like /weekly-contest-367/, which gives no page number skipping capabilities.

The only way to navigate through pages on the current site is with the buttons below the ratings, which only allows you to move two pages back or forward (Shown below).
![image](https://github.com/baoliay2008/lccn_predictor/assets/121001035/ef11c8be-a1bd-4d09-833d-668c8965df01)

This is very inconvenient, as there are hundreds of pages per contest. Could we change the URL routing system or add a button on the page navigator that allows the user to specify which page they would like to navigate to? I would be happy to work on this issue.

**Comment by baoliay2008** [comment]
Hi, thanks for your suggestion. I found this inconvenient, too. I will add page number into URL router in the next version.
