### ISSUE TITLE
biweekly-contest-116 ratings not up yet

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#30]
biweekly-contest-116 ratings not up yet at https://lccn.lbao.site/predicted/biweekly-contest-116
it's been about 2 & 1/2 hours post contest

===

ideally,

1 https://lccn.lbao.site/ should show   Biweekly Contest 116   after contest is completed

Currently shows below:
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/f8681bbf-c345-49e3-999f-96f6f555d8cd)

2 https://lccn.lbao.site/predicted/biweekly-contest-116
should show proper message of why there is delay
For example:  "US Data not present. Check back after few hours", etc.

Currently shows below:
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/b6713982-50cf-4b96-a36b-9c28d0b8e794)

===

thanks for your hard work @baoliay2008

**Comment by baoliay2008** [comment]
Thank you for your reminder, I'm looking into it.

**Comment by manoharreddyporeddy** [comment]
May be, we should login as a some test user
and take request using

```
> Chrome > Right click > Inspect
> Right click on API > Copy > Copy as fetch / node.js fetch
```

So that we can send requests using `cookies`
Or something different to make APIs work

===

I have raised ticket on leetcode for now:

https://support.leetcode.com/hc/en-us/requests/207792

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/88462378-8801-4088-85aa-15f0c1f469e0)
