### ISSUE TITLE
[BUG] Site stuck in loading phase

### ISSUE THREAD

**Issue by Tanuj-Taneja1** [baoliay2008/lccn_predictor#31]
**Description**
The site [https://lccn.lbao.site/](url) is not loading properly
Checked on multiple devices

**Screenshot**
![image](https://github.com/baoliay2008/lccn_predictor/assets/94695078/97bbc2e0-63b9-4a24-a247-d6a380fd3717)

**Comment by baoliay2008** [comment]
Works on my laptop and phones. Could you please clear your browser cache and try again?

**Comment by baoliay2008** [comment]
It should be the front-end caIt could be the frontend cache issue. Please let me know if you can access it by clearing your browser cache.

**Comment by Tanuj-Taneja1** [comment]
Still not working for me after removing browser cache
Also tried on different browsers still the same issue

**Comment by Tanuj-Taneja1** [comment]
@baoliay2008 I even tried opening the site in my brothers phone still stuck at loading
PS
if your site is working can you pls tell me my recent rank on leetcode biweekly 116
id -tanuj_taneja

**Comment by baoliay2008** [comment]
@Tanuj-Taneja1  Thank you for your quick response. I have just re-published the front-end code. Please try again; this is a significant bug. Please let me know if you can open it now.

**Comment by baoliay2008** [comment]
@Tanuj-Taneja1  Sorry, it's not working. I'm still fixing some backend code.

**Comment by Aasrish** [comment]
@baoliay2008 I think it's working now, I just opened it, but yes, it is taking some time in opening.

**Comment by baoliay2008** [comment]
@Aasrish  Thank you for your response. It's about a cache issue related to the frontend rebuild. Let's address this issue in the future. Kindly leave this issue open, and I will solve it later.

**Comment by Tanuj-Taneja1** [comment]
@Aasrish how long did it took for you, it is still not opening for me

**Comment by baoliay2008** [comment]
@Tanuj-Taneja1 It's weird, please give it a try using **private mode**.

**Comment by baoliay2008** [comment]
It's normal for it to take longer than before because all static files will be downloaded again since I reset the cache.

**Comment by Tanuj-Taneja1** [comment]
Nope still the same
![image](https://github.com/baoliay2008/lccn_predictor/assets/94695078/57e9de99-5fc1-4803-86eb-0aad377923bd)

**Comment by baoliay2008** [comment]
@Tanuj-Taneja1 How about now? There was an update. Everything should be normal now.

**Comment by Tanuj-Taneja1** [comment]
@baoliay2008 yes the site is opening on 1 of my devices but still not all of them.
But thanks anyway got to know my rank change

**Comment by manoharreddyporeddy** [comment]
Same issue for me too

But after 1 minute wait, page loaded
On each rank check, 10 seconds wait is required now.

**Comment by sam20908** [comment]
Same issue for me, using Windows 11 and Edge browser.

What is the app doing to take so long?

**Comment by baoliay2008** [comment]
@manoharreddyporeddy @sam20908 Hi, this issue is affecting some users. I have just disabled a front-end analytics tool, which is the only thing that may be causing this error, as some client-side networks may not have access to this public tool. Please let me know if things are working well now.

**Comment by manoharreddyporeddy** [comment]
Today it is working. All good.

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/08eee292-3da2-4285-8205-c7fc3d3b4831)

**Comment by baoliay2008** [comment]
OK, thank you. @manoharreddyporeddy

**Comment by sam20908** [comment]
It works for me, but I have to wait like 5 minutes

**Comment by baoliay2008** [comment]
@sam20908 It shuold take less than 1 second.

Could you please provide a screenshot of 'Developer Tools (F12) -> Network'? Without it, I won't be able to identify the root cause. Some people may have unintentionally clicked the 'Disable Cache' option in their browser, causing it to download static files every time, but it shouldn't take so long to visit.

**Comment by sam20908** [comment]
![image](https://github.com/baoliay2008/lccn_predictor/assets/18388795/1505d32f-433b-4942-bd01-13cbcc63915b)

**Comment by sam20908** [comment]
Ah it takes very short now I forgot I just cleared my browser cache :)
