### ISSUE TITLE
Weekly contest 373 - Ratings are not correct, after 45 mins post contest

### ISSUE THREAD

**Issue by manoharreddyporeddy** [baoliay2008/lccn_predictor#33]
https://lccn.lbao.site/predicted/weekly-contest-373
user - [razorsharp7](https://leetcode.com/razorsharp7)

![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/a8c96ca4-c4cc-462c-bb3b-cbed98433477)

https://leetcode.com/contest/weekly-contest-373/ranking/196/
![image](https://github.com/baoliay2008/lccn_predictor/assets/8236389/3ead6d18-c6f0-4b42-a8ee-8f1ff8afe69b)

**Comment by baoliay2008** [comment]
This should be same as #25

**Comment by baoliay2008** [comment]
prediction was correct. close this issue.
