### ISSUE TITLE
Number of successful submissions differs from leetcode

### ISSUE THREAD

**Issue by DmitryBokovikov** [baoliay2008/lccn_predictor#34]
For example
![25-12-2023 22-12-27](https://github.com/baoliay2008/lccn_predictor/assets/25640540/7cbca800-4785-4d8e-bbdc-46dd37e576a8)
![25-12-2023 22-12-52](https://github.com/baoliay2008/lccn_predictor/assets/25640540/0020a33f-22e3-4746-bb09-a71181ab2ed7)
Predictor show 9868 successful attempts and leetcode shows 8532

**Comment by baoliay2008** [comment]
Hi, @DmitryBokovikov  Thanks for your comment. Please note that LeetCode has another data region in China. The rating algorithm applies to both the US and CN data regions, so successful submissions in the CN region are also included.

Same question as #25  and #33

**Comment by DmitryBokovikov** [comment]
Thanks 👍
