### ISSUE TITLE
[BUG] Wrong predictions in Biweekly 122

### ISSUE THREAD

**Issue by Tanuj-Taneja1** [baoliay2008/lccn_predictor#46]
Here you can see the number of users who successfully submitted the question 1 is almost 10 less than what is displayed on https://lccn.lbao.site/predicted/biweekly-contest-122
![IMG-20240120-WA0004](https://github.com/baoliay2008/lccn_predictor/assets/94695078/4789d3bb-6520-413f-a319-13e501576bbc)

![Screenshot_2024-01-20-22-21-16-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/baoliay2008/lccn_predictor/assets/94695078/cd775ff7-da10-4aab-8e40-1eddea888be3)

**Comment by Donavern** [comment]
Seems like it is just missing US users

**Comment by ashuthe1** [comment]
Yes, it's missing US users.

**Comment by baoliay2008** [comment]
@Tanuj-Taneja1  Thank you for reporting this issue. I looked into it, and the data for two regions hasn't been merged by LeetCode. I'm trying to fix it.

**Comment by Donavern** [comment]
Thanks for being quick to fix the issues every time ❤️‍🔥
