### ISSUE TITLE
Weekly Contest 335 data may have error

### ISSUE THREAD

**Issue by Owenxh** [baoliay2008/lccn_predictor#6]
Can't find score of China area.

**Comment by baoliay2008** [comment]
Hi, same with issue #1 , leetcode.com didn't sync with leetcode.cn
Maybe it's not a good idea to run at a given time (now is 15 minutes after the contest has finished), I will add more code to address this problem.

**Comment by baoliay2008** [comment]
This bug has been fixed a long time ago, and it has been observed for a while. Unless there's a glitch in the official servers, it should be fine. Please see #1
