### ISSUE TITLE
Improve Theme Selection Process

### ISSUE THREAD

**Issue by imsachin49** [baoliay2008/lccn_predictor#67]
- Currently, accessing available themes requires scrolling through the home page. To streamline this process, we can implement a scrollbar specifically for browsing available themes on the theme section only. This will offer users a more efficient and organized way to explore our selection of themes.

- Additionally, I suggest enhancing the user experience by implementing the feature where clicking the theme button toggles the visibility of the theme list. This way, users can easily open and close the theme list without having to navigate away.

- I've created a video demonstrating the issue. You can watch it [here](https://github.com/baoliay2008/lccn_predictor/assets/108334265/56793857-3fd2-4260-a5fb-7b7515624381).

- I'm interested in working on this issue and would like to contribute to the project. Could this issue be assigned to me? I believe I can effectively implement these improvements and ensure a better user experience. Looking forward to collaborating with the team on this.

  **Thank you!**

**Comment by baoliay2008** [comment]
@imsachin49 Thank you for your suggestion.

- About the scrollbar, while I don't think it's necessary, there's no harm in adding one. We welcome a pull request if you'd like to contribute.

- For clicking the theme button to toggle the visibility of the theme list, I understand what you're looking for. You'd like it to work similarly to the `<details>` tag. Although I don't see it as critical, we'd be happy to consider a pull request if you want to propose a solution.

**Comment by baoliay2008** [comment]
Thanks for your contribution!
