### ISSUE TITLE
Feature request: Page selector

### ISSUE THREAD

**Issue by lone17** [baoliay2008/lccn_predictor#79]
Thank you for making this tool.

It would be nice if it allows me to choose any page I want without having to click multiple times.

**Comment by baoliay2008** [comment]
@lone17 Thanks for your issue. I will add the page parameters this week.

**Comment by lone17** [comment]
> @lone17 Thanks for your issue. I will add the page parameters this week.

Nice ! Thank you.

**Comment by baoliay2008** [comment]
Solved in PR #81 Now you can visit the page using a URL parameter like this: https://lccn.lbao.site/predicted/weekly-contest-415/512
