### ISSUE TITLE
Biweekly Contest 139 users missing on leaderboard.

### ISSUE THREAD

**Issue by SP321** [baoliay2008/lccn_predictor#80]
shows empty list when searching for few participated Users.

**Comment by baoliay2008** [comment]
@SP321 Thanks for raising the issue. 

Could you provide some examples? I just checked, and it’s consistent with the official leaderboard. Please make sure you used the correct username, as it is case-sensitive.

**Comment by SP321** [comment]
> @SP321 Thanks for raising the issue.
> 
> Could you provide some examples? I just checked, and it’s consistent with the official leaderboard. Please make sure you used the correct user_slug, as it is case-sensitive.

My username "Sandeep_P" Is missing in latest contest but visible in previous contests.

**Comment by baoliay2008** [comment]
@SP321 Searching for “sandeep_p” returns the record. I will look into what happened with the user_slug
